name: Clean up PR cache

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  preprocess:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Clean up PR cache
        shell: bash -l {0}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git push origin --delete _cookbook_data_PR${{ github.event.number }}
